name: baitapfl
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.17
  google_fonts: ^5.0.0
  mobile_scanner: ^3.0.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.0
  http: ^1.2.2
  fluttertoast: ^8.0.9
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  flutter_vlc_player: ^7.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/qrcode.gif
